### ISSUE TITLE
如何根据字符串资源ID获取字符串

### ISSUE THREAD

**Issue by ljmljt** [kin9-0rz/apkutils#30]
你好，请问一下这个问题：
解析Manifest文件部分值为字符串资源ID，如何匹配上对应的字符串

**Comment by kin9-0rz** [comment]
不好意思，才看到。现在我主要在gitee上干活，偶尔才上GitHub。

Android 的资源ID，统一存放在resource.arsc文件里面，需要找什么直接去arsc找就行了。

譬如，android:label="@string/app_name"，表示你要到values/strings里面去找，`<string name="app_name">APP名字</string>`。
