### ISSUE TITLE
use pyinstaller import apkuilts fail

### ISSUE THREAD

**Issue by OneBranchAlone** [kin9-0rz/apkutils#31]
Failed to execute script 'APKAnalysis' due to unhandledexception: need to copy the

sdk/platforms/android-?/data/res/values/public.xml here
what is 
sdk/platforms/android-?/data/res/values/public.xml

**Comment by OneBranchAlone** [comment]
就是引用apkutils后想用pyinstaller打包成工具，但是运行的时候缺少xml文件
![Uploading mmexport1645100871071.png…]()

**Comment by OneBranchAlone** [comment]
![Uploading mmexport1645100871071.png…]()

**Comment by DyLenpOki** [comment]
解决方案是什么？

**Comment by DyLenpOki** [comment]
@kin9-0rz 请问解决办法是什么？

**Comment by DyLenpOki** [comment]
解决办法：

![Image](https://github.com/user-attachments/assets/c00d3684-a8de-46a2-8e7e-2d35cfff654d)
