### ISSUE TITLE
可能存在的侵犯开源协议

### ISSUE THREAD

**Issue by Young-Lord** [kin9-0rz/apkutils#33]
您的代码中用到了 https://github.com/Storyyeller/enjarify 项目，根据 Apache License 2.0，您必须在您的项目说明文件中加入此repo的地址（即：来源信息），并在您修改过的 https://github.com/kin9-0rz/apkutils/blob/master/apkutils/dex/dexparser.py 等文件中注明修改。
另外，`axmlparser.py`是来自您以前的项目 https://github.com/kin9-0rz/axmlparser ，本项目却使用了非 `GPL-3.0`的协议。尽管显然你不会举报自己侵权，但这样可能会给使用/二次开发本项目的人（比如我）带来潜在的侵权问题。或者说，我们可能无法肯定这部分代码应当以何种协议使用。

另，能写写docstring和type hint吗……没有这些会让人用的很难受

**Comment by kin9-0rz** [comment]
感谢您的反馈，这些都很有参考价值，未来有时间我再补上，但是不保证短时间能够更新上。

如果您很着急，有两个方案：
1. 拷贝一份，想怎么改都行，根据自己的需求改。
2. 使用 Androguard 或 enjarify，进行二次开发。(Androguard支持dex和arsc、axml的解析；enjarify仅仅支持 dex 的解析)
3. fork 一份 gitee 的代码，修改完毕后，我合并一下。
